feat: get products by category id
intive/patronage22_lublin_js_api pull request #25
Opened 2022-04-04 17:28 UTC by DmytroTarasiuk

2022-04-04 17:30 UTC, ostafinskim approved these changes

2022-04-05 07:48 UTC, dblach-intive requested changes

2022-04-05 07:48 UTC, dblach-intive commented on controllers/productController.js
> +    where: { category: category.title },
We cant get by title, we can get by slug if we have one ? if not we have to get by ID

2022-04-05 07:48 UTC, dblach-intive commented on controllers/productController.js
> +    throw new CustomAPIError("Please provide details for new product", 400);
Dmytro we're using single quotes in API repo, please change it from " to ' and remove all these changes

2022-04-11 12:41 UTC, dblach-intive approved these changes

2022-04-11 17:06 UTC, merged